In [265]:
from faulthandler import dump_traceback

import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns
import numpy as np
from pandas.conftest import ordered

# path1 = "../ML-Movies-Recommender-Redo/datasets/tmdb_5000_credits.csv"
# pt
df_credits = pd.read_csv("../ML-Movies-Recommender-Redo/datasets/tmdb_5000_credits.csv")
df_movies = pd.read_csv("../ML-Movies-Recommender-Redo/datasets/tmdb_5000_movies.csv")

In [266]:
df_credits.shape, df_movies.shape

((4803, 4), (4803, 20))

In [267]:
df_credits.head()

movie_id                                     title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [268]:
df_movies.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  \
0  [{"name": "Ingenious Film Partners", "id": 289...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...   
4        [{"name": "Walt Disney Pictures", "id": 2}]   

                                production_countries release_date     revenue  \
0  [{"iso_3166_1": "US", "name": "United States o...   2009-12-10  2787965087   
1  [{"iso_3166_1": "US", "name": "United States o...   2007-05-19   961000000   
2  [{"iso_3166_1": "GB", "name": "United Kingdom"...   2015-10-26   880674609   
3  [{"iso_3166_1": "US", "name": "United States o...   2012-07-16  1084939099   
4  [{"iso_3166_1": "US", "name": "United States o...   2012-03-07   284139100   

   runtime                                   spoken_languages    status  \
0    162.0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1    169.0           [{"iso_639_1": "en", "name": "English"}]  Released   
2    148.0  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3    165.0           [{"iso_639_1": "en", "name": "English"}]  Released   
4    132.0           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title  vote_average  vote_count  
0                                    Avatar           7.2       11800  
1  Pirates of the Caribbean: At World's End           6.9        4500  
2                                   Spectre           6.3        4466  
3                     The Dark Knight Rises           7.6        9106  
4                               John Carter           6.1        2124

#### Merge column

In [269]:
df_movies_credits = pd.merge(df_movies, df_credits, left_on='id', right_on='movie_id', how='inner')
df_movies_credits.head()

budget                                             genres  \
0  237000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  300000000  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  245000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  250000000  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  260000000  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...                en   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...                en   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...                en   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...                en   
4  [{"id": 818, "name": "based on novel"}, {"id":...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577   
1  Captain Barbossa, long believed to be dead, ha...  139.082615   
2  A cryptic message from Bond’s past sends him o...  107.376788   
3  Following the death of District Attorney Harve...  112.312950   
4  John Carter is a war-weary, former military ca...   43.926995   

                                production_companies  ...  \
0  [{"name": "Ingenious Film Partners", "id": 289...  ...   
1  [{"name": "Walt Disney Pictures", "id": 2}, {"...  ...   
2  [{"name": "Columbia Pictures", "id": 5}, {"nam...  ...   
3  [{"name": "Legendary Pictures", "id": 923}, {"...  ...   
4        [{"name": "Walt Disney Pictures", "id": 2}]  ...   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                    title_x vote_average vote_count movie_id  \
0                                    Avatar          7.2      11800    19995   
1  Pirates of the Caribbean: At World's End          6.9       4500      285   
2                                   Spectre          6.3       4466   206647   
3                     The Dark Knight Rises          7.6       9106    49026   
4                               John Carter          6.1       2124    49529   

                                    title_y  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce W

#### Reduce columns which not important

In [270]:
df_movies_credits.drop(['budget','homepage','original_language','popularity','production_companies','production_countries','release_date','revenue','runtime','spoken_languages','status','title_x','vote_average','vote_count','title_y','id','tagline'], axis=1, inplace=True)

In [271]:
df_movies_credits.head()

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   
2  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
3  [{"id": 28, "name": "Action"}, {"id": 80, "nam...   
4  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   
2  [{"id": 470, "name": "spy"}, {"id": 818, "name...   
3  [{"id": 849, "name": "dc comics"}, {"id": 853,...   
4  [{"id": 818, "name": "based on novel"}, {"id":...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  movie_id  \
0  In the 22nd century, a paraplegic Marine is di...     19995   
1  Captain Barbossa, long believed to be dead, ha...       285   
2  A cryptic message from Bond’s past sends him o...    206647   
3  Following the death of District Attorney Harve...     49026   
4  John Carter is a war-weary, former military ca...     49529   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   
3  [{"cast_id": 2, "character": "Bruce Wayne / Ba...   
4  [{"cast_id": 5, "character": "John Carter", "c...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...  
3  [{"credit_id": "52fe4781c3a36847f81398c3", "de...  
4  [{"credit_id": "52fe479ac3a36847f813eaa3", "de...

In [272]:
df_movies_credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   genres          4803 non-null   object
 1   keywords        4803 non-null   object
 2   original_title  4803 non-null   object
 3   overview        4800 non-null   object
 4   movie_id        4803 non-null   int64 
 5   cast            4803 non-null   object
 6   crew            4803 non-null   object
dtypes: int64(1), object(6)
memory usage: 262.8+ KB


#### Check N/A values

In [273]:
df_movies_credits.isnull().sum()

genres            0
keywords          0
original_title    0
overview          3
movie_id          0
cast              0
crew              0
dtype: int64

In [274]:
df_movies_credits.dropna(inplace=True)

In [275]:
df_movies_credits.isnull().sum()

genres            0
keywords          0
original_title    0
overview          0
movie_id          0
cast              0
crew              0
dtype: int64

#### Check duplicated values

In [276]:
df_movies_credits.duplicated().sum()

0

### Convert values from each column

In [277]:
df_movies_credits.head(2)

genres  \
0  [{"id": 28, "name": "Action"}, {"id": 12, "nam...   
1  [{"id": 12, "name": "Adventure"}, {"id": 14, "...   

                                            keywords  \
0  [{"id": 1463, "name": "culture clash"}, {"id":...   
1  [{"id": 270, "name": "ocean"}, {"id": 726, "na...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  movie_id  \
0  In the 22nd century, a paraplegic Marine is di...     19995   
1  Captain Barbossa, long believed to be dead, ha...       285   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

In [278]:
df_movies_credits['genres'].iloc[0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [279]:
import ast

temp =ast.literal_eval(df_movies_credits['genres'].iloc[0])
temp

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

#### Get name of genres, keywords

In [280]:
holder = []
for data in temp:
    holder.append(data['name'])
holder

['Action', 'Adventure', 'Fantasy', 'Science Fiction']

In [281]:
def convert_data(data):
    list_convert = []
    for value in ast.literal_eval(data):
        list_convert.append(value['name'])
    return list_convert

df_movies_credits['genres'].apply(convert_data)


0       [Action, Adventure, Fantasy, Science Fiction]
1                        [Adventure, Fantasy, Action]
2                          [Action, Adventure, Crime]
3                    [Action, Crime, Drama, Thriller]
4                [Action, Adventure, Science Fiction]
                            ...                      
4798                        [Action, Crime, Thriller]
4799                                [Comedy, Romance]
4800               [Comedy, Drama, Romance, TV Movie]
4801                                               []
4802                                    [Documentary]
Name: genres, Length: 4800, dtype: object

In [282]:
df_movies_credits['genres']=df_movies_credits['genres'].apply(convert_data)
df_movies_credits['keywords']=df_movies_credits['keywords'].apply(convert_data)
df_movies_credits.head(3)

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   

                                            overview  movie_id  \
0  In the 22nd century, a paraplegic Marine is di...     19995   
1  Captain Barbossa, long believed to be dead, ha...       285   
2  A cryptic message from Bond’s past sends him o...    206647   

                                                cast  \
0  [{"cast_id": 242, "character": "Jake Sully", "...   
1  [{"cast_id": 4, "character": "Captain Jack Spa...   
2  [{"cast_id": 1, "character": "James Bond", "cr...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...  
2  [{"credit_id": "54805967c3a36829b5002c41", "de...

#### Get 4 names of actors from cast 

In [283]:
df_movies_credits.iloc[0]['cast']

'[{"cast_id": 242, "character": "Jake Sully", "credit_id": "5602a8a7c3a3685532001c9a", "gender": 2, "id": 65731, "name": "Sam Worthington", "order": 0}, {"cast_id": 3, "character": "Neytiri", "credit_id": "52fe48009251416c750ac9cb", "gender": 1, "id": 8691, "name": "Zoe Saldana", "order": 1}, {"cast_id": 25, "character": "Dr. Grace Augustine", "credit_id": "52fe48009251416c750aca39", "gender": 1, "id": 10205, "name": "Sigourney Weaver", "order": 2}, {"cast_id": 4, "character": "Col. Quaritch", "credit_id": "52fe48009251416c750ac9cf", "gender": 2, "id": 32747, "name": "Stephen Lang", "order": 3}, {"cast_id": 5, "character": "Trudy Chacon", "credit_id": "52fe48009251416c750ac9d3", "gender": 1, "id": 17647, "name": "Michelle Rodriguez", "order": 4}, {"cast_id": 8, "character": "Selfridge", "credit_id": "52fe48009251416c750ac9e1", "gender": 2, "id": 1771, "name": "Giovanni Ribisi", "order": 5}, {"cast_id": 7, "character": "Norm Spellman", "credit_id": "52fe48009251416c750ac9dd", "gender": 

In [284]:
temp2 = ast.literal_eval(df_movies_credits['cast'].iloc[0])
temp2

[{'cast_id': 242,
  'character': 'Jake Sully',
  'credit_id': '5602a8a7c3a3685532001c9a',
  'gender': 2,
  'id': 65731,
  'name': 'Sam Worthington',
  'order': 0},
 {'cast_id': 3,
  'character': 'Neytiri',
  'credit_id': '52fe48009251416c750ac9cb',
  'gender': 1,
  'id': 8691,
  'name': 'Zoe Saldana',
  'order': 1},
 {'cast_id': 25,
  'character': 'Dr. Grace Augustine',
  'credit_id': '52fe48009251416c750aca39',
  'gender': 1,
  'id': 10205,
  'name': 'Sigourney Weaver',
  'order': 2},
 {'cast_id': 4,
  'character': 'Col. Quaritch',
  'credit_id': '52fe48009251416c750ac9cf',
  'gender': 2,
  'id': 32747,
  'name': 'Stephen Lang',
  'order': 3},
 {'cast_id': 5,
  'character': 'Trudy Chacon',
  'credit_id': '52fe48009251416c750ac9d3',
  'gender': 1,
  'id': 17647,
  'name': 'Michelle Rodriguez',
  'order': 4},
 {'cast_id': 8,
  'character': 'Selfridge',
  'credit_id': '52fe48009251416c750ac9e1',
  'gender': 2,
  'id': 1771,
  'name': 'Giovanni Ribisi',
  'order': 5},
 {'cast_id': 7,
  'c

In [285]:
# We will get the first 4 actors
def convert_cast(data):
    list_cast = []
    for key, item in enumerate(ast.literal_eval(data)):
        if key < 4:
            list_cast.append(item['name'])
    return list_cast

convert_cast(df_movies_credits.iloc[0]['cast'])

['Sam Worthington', 'Zoe Saldana', 'Sigourney Weaver', 'Stephen Lang']

In [286]:
df_movies_credits['cast'].apply(convert_cast)

0       [Sam Worthington, Zoe Saldana, Sigourney Weave...
1       [Johnny Depp, Orlando Bloom, Keira Knightley, ...
2       [Daniel Craig, Christoph Waltz, Léa Seydoux, R...
3       [Christian Bale, Michael Caine, Gary Oldman, A...
4       [Taylor Kitsch, Lynn Collins, Samantha Morton,...
                              ...                        
4798    [Carlos Gallardo, Jaime de Hoyos, Peter Marqua...
4799    [Edward Burns, Kerry Bishé, Marsha Dietlein, C...
4800    [Eric Mabius, Kristin Booth, Crystal Lowe, Geo...
4801    [Daniel Henney, Eliza Coupe, Bill Paxton, Alan...
4802    [Drew Barrymore, Brian Herzlinger, Corey Feldm...
Name: cast, Length: 4800, dtype: object

In [287]:
df_movies_credits['cast']=df_movies_credits['cast'].apply(convert_cast)
df_movies_credits.head(2)

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  movie_id  \
0  In the 22nd century, a paraplegic Marine is di...     19995   
1  Captain Barbossa, long believed to be dead, ha...       285   

                                                cast  \
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...   
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...   

                                                crew  
0  [{"credit_id": "52fe48009251416c750aca23", "de...  
1  [{"credit_id": "52fe4232c3a36847f800b579", "de...

#### Convert information from crew --> get director

In [288]:
df_movies_credits.iloc[0]['crew']

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"},

In [289]:
temp3 =ast.literal_eval(df_movies_credits.iloc[0]['crew'])
temp3

[{'credit_id': '52fe48009251416c750aca23',
  'department': 'Editing',
  'gender': 0,
  'id': 1721,
  'job': 'Editor',
  'name': 'Stephen E. Rivkin'},
 {'credit_id': '539c47ecc3a36810e3001f87',
  'department': 'Art',
  'gender': 2,
  'id': 496,
  'job': 'Production Design',
  'name': 'Rick Carter'},
 {'credit_id': '54491c89c3a3680fb4001cf7',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Sound Designer',
  'name': 'Christopher Boyes'},
 {'credit_id': '54491cb70e0a267480001bd0',
  'department': 'Sound',
  'gender': 0,
  'id': 900,
  'job': 'Supervising Sound Editor',
  'name': 'Christopher Boyes'},
 {'credit_id': '539c4a4cc3a36810c9002101',
  'department': 'Production',
  'gender': 1,
  'id': 1262,
  'job': 'Casting',
  'name': 'Mali Finn'},
 {'credit_id': '5544ee3b925141499f0008fc',
  'department': 'Sound',
  'gender': 2,
  'id': 1729,
  'job': 'Original Music Composer',
  'name': 'James Horner'},
 {'credit_id': '52fe48009251416c750ac9c3',
  'department': 'Directing',
  

In [290]:
list = []
for key, value in enumerate(temp3):
    if value['job'] == 'Director':
        list.append(value['name'])
list

['James Cameron']

In [291]:
def convert_director(data):
    list_director = []
    for key, value in enumerate(ast.literal_eval(data)):
        if value['job'] == 'Director':
            list_director.append(value['name'])
    return list_director
            
df_movies_credits['crew'].apply(convert_director)[0]

['James Cameron']

In [292]:
df_movies_credits['crew']=df_movies_credits['crew'].apply(convert_director)
df_movies_credits.head(2)

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  movie_id  \
0  In the 22nd century, a paraplegic Marine is di...     19995   
1  Captain Barbossa, long believed to be dead, ha...       285   

                                                cast              crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...   [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...  [Gore Verbinski]

In [293]:
# Split overview to the list
df_movies_credits['overview'].str.split()

0       [In, the, 22nd, century,, a, paraplegic, Marin...
1       [Captain, Barbossa,, long, believed, to, be, d...
2       [A, cryptic, message, from, Bond’s, past, send...
3       [Following, the, death, of, District, Attorney...
4       [John, Carter, is, a, war-weary,, former, mili...
                              ...                        
4798    [El, Mariachi, just, wants, to, play, his, gui...
4799    [A, newlywed, couple's, honeymoon, is, upended...
4800    ["Signed,, Sealed,, Delivered", introduces, a,...
4801    [When, ambitious, New, York, attorney, Sam, is...
4802    [Ever, since, the, second, grade, when, he, fi...
Name: overview, Length: 4800, dtype: object

In [294]:
df_movies_credits['overview']=df_movies_credits['overview'].str.split()

In [295]:
df_movies_credits.head()

genres  \
0  [Action, Adventure, Fantasy, Science Fiction]   
1                   [Adventure, Fantasy, Action]   
2                     [Action, Adventure, Crime]   
3               [Action, Crime, Drama, Thriller]   
4           [Action, Adventure, Science Fiction]   

                                            keywords  \
0  [culture clash, future, space war, space colon...   
1  [ocean, drug abuse, exotic island, east india ...   
2  [spy, based on novel, secret agent, sequel, mi...   
3  [dc comics, crime fighter, terrorist, secret i...   
4  [based on novel, mars, medallion, space travel...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  movie_id  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     19995   
1  [Captain, Barbossa,, long, believed, to, be, d...       285   
2  [A, cryptic, message, from, Bond’s, past, send...    206647   
3  [Following, the, death, of, District, Attorney...     49026   
4  [John, Carter, is, a, war-weary,, former, mili...     49529   

                                                cast                 crew  
0  [Sam Worthington, Zoe Saldana, Sigourney Weave...      [James Cameron]  
1  [Johnny Depp, Orlando Bloom, Keira Knightley, ...     [Gore Verbinski]  
2  [Daniel Craig, Christoph Waltz, Léa Seydoux, R...         [Sam Mendes]  
3  [Christian Bale, Michael Caine, Gary Oldman, A...  [Christopher Nolan]  
4  [Taylor Kitsch, Lynn Collins, Samantha Morton,...     [Andrew Stanton]

#### Get lower each words from columns

In [296]:
temp4=df_movies_credits['keywords'][0]
temp4

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [297]:
list = []
for i in temp4:
    list.append(i.replace(" ",""))
list

['cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d']

In [298]:
def replace_space(data):
    list = []
    for i in data :
        list.append(i.replace(" ",""))
    return list
replace_space(df_movies_credits['keywords'][0])


['cultureclash',
 'future',
 'spacewar',
 'spacecolony',
 'society',
 'spacetravel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alienplanet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'loveaffair',
 'antiwar',
 'powerrelations',
 'mindandsoul',
 '3d']

In [299]:
df_movies_credits['keywords'] = df_movies_credits['keywords'].apply(replace_space)
df_movies_credits['genres'] = df_movies_credits['genres'].apply(replace_space)
df_movies_credits['cast'] = df_movies_credits['cast'].apply(replace_space)
df_movies_credits['crew'] = df_movies_credits['crew'].apply(replace_space)

In [300]:
df_movies_credits.head(2)

genres  \
0  [Action, Adventure, Fantasy, ScienceFiction]   
1                  [Adventure, Fantasy, Action]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   

                                            overview  movie_id  \
0  [In, the, 22nd, century,, a, paraplegic, Marin...     19995   
1  [Captain, Barbossa,, long, believed, to, be, d...       285   

                                                cast             crew  
0  [SamWorthington, ZoeSaldana, SigourneyWeaver, ...   [JamesCameron]  
1  [JohnnyDepp, OrlandoBloom, KeiraKnightley, Ste...  [GoreVerbinski]

#### Get lower words

In [301]:
list = []
for i in df_movies_credits['cast'][0]:
    list.append(i.lower())
list

['samworthington', 'zoesaldana', 'sigourneyweaver', 'stephenlang']

In [302]:
def lowercase(data):
    list = []
    for word in data:
        list.append(word.lower())
    return list

lowercase(df_movies_credits['cast'][0])

['samworthington', 'zoesaldana', 'sigourneyweaver', 'stephenlang']

In [303]:
df_movies_credits['keywords'] = df_movies_credits['keywords'].apply(lowercase)
df_movies_credits['genres'] = df_movies_credits['genres'].apply(lowercase)
df_movies_credits['cast'] = df_movies_credits['cast'].apply(lowercase)
df_movies_credits['crew'] = df_movies_credits['crew'].apply(lowercase)
df_movies_credits['overview'] = df_movies_credits['overview'].apply(lowercase)

In [304]:
df_movies_credits.head()

genres  \
0  [action, adventure, fantasy, sciencefiction]   
1                  [adventure, fantasy, action]   
2                    [action, adventure, crime]   
3              [action, crime, drama, thriller]   
4           [action, adventure, sciencefiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  movie_id  \
0  [in, the, 22nd, century,, a, paraplegic, marin...     19995   
1  [captain, barbossa,, long, believed, to, be, d...       285   
2  [a, cryptic, message, from, bond’s, past, send...    206647   
3  [following, the, death, of, district, attorney...     49026   
4  [john, carter, is, a, war-weary,, former, mili...     49529   

                                                cast                crew  
0  [samworthington, zoesaldana, sigourneyweaver, ...      [jamescameron]  
1  [johnnydepp, orlandobloom, keiraknightley, ste...     [goreverbinski]  
2  [danielcraig, christophwaltz, léaseydoux, ralp...         [sammendes]  
3  [christianbale, michaelcaine, garyoldman, anne...  [christophernolan]  
4  [taylorkitsch, lynncollins, samanthamorton, wi...     [andrewstanton]

#### Create the tag which get all features : genres, keywords, overview, cast, crew

In [305]:
df_movies_credits['tag'] = df_movies_credits['overview'] + df_movies_credits['keywords']+ df_movies_credits['genres'] + df_movies_credits['cast']  + df_movies_credits['crew']
df_movies_credits['tag'].head(3)

0    [in, the, 22nd, century,, a, paraplegic, marin...
1    [captain, barbossa,, long, believed, to, be, d...
2    [a, cryptic, message, from, bond’s, past, send...
Name: tag, dtype: object

--> Join all words in tag

In [306]:
df_movies_credits['tag'].apply(lambda x : " ".join(x))[0]

'in the 22nd century, a paraplegic marine is dispatched to the moon pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d action adventure fantasy sciencefiction samworthington zoesaldana sigourneyweaver stephenlang jamescameron'

In [310]:
df_movies_credits['tag']=df_movies_credits['tag'].apply(lambda x : " ".join(x))
df_movies_credits.head()

genres  \
0  [action, adventure, fantasy, sciencefiction]   
1                  [adventure, fantasy, action]   
2                    [action, adventure, crime]   
3              [action, crime, drama, thriller]   
4           [action, adventure, sciencefiction]   

                                            keywords  \
0  [cultureclash, future, spacewar, spacecolony, ...   
1  [ocean, drugabuse, exoticisland, eastindiatrad...   
2  [spy, basedonnovel, secretagent, sequel, mi6, ...   
3  [dccomics, crimefighter, terrorist, secretiden...   
4  [basedonnovel, mars, medallion, spacetravel, p...   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  movie_id  \
0  [in, the, 22nd, century,, a, paraplegic, marin...     19995   
1  [captain, barbossa,, long, believed, to, be, d...       285   
2  [a, cryptic, message, from, bond’s, past, send...    206647   
3  [following, the, death, of, district, attorney...     49026   
4  [john, carter, is, a, war-weary,, former, mili...     49529   

                                                cast                crew  \
0  [samworthington, zoesaldana, sigourneyweaver, ...      [jamescameron]   
1  [johnnydepp, orlandobloom, keiraknightley, ste...     [goreverbinski]   
2  [danielcraig, christophwaltz, léaseydoux, ralp...         [sammendes]   
3  [christianbale, michaelcaine, garyoldman, anne...  [christophernolan]   
4  [taylorkitsch, lynncollins, samanthamorton, wi...     [andrewstanton]   

                                                 tag  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

#### Filter value features --> get the final convert dataframe

In [311]:
df_movies_final = df_movies_credits[['movie_id','original_title','tag']]
df_movies_final.head()

movie_id                            original_title  \
0     19995                                    Avatar   
1       285  Pirates of the Caribbean: At World's End   
2    206647                                   Spectre   
3     49026                     The Dark Knight Rises   
4     49529                               John Carter   

                                                 tag  
0  in the 22nd century, a paraplegic marine is di...  
1  captain barbossa, long believed to be dead, ha...  
2  a cryptic message from bond’s past sends him o...  
3  following the death of district attorney harve...  
4  john carter is a war-weary, former military ca...

#### Determine similarity

In [413]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

#Create similarity from cv and vector --> hold all character from tag and transform to number in array
cv = CountVectorizer(max_features=5000, stop_words='english')
vector = cv.fit_transform(df_movies_final['tag'])
similarity = cosine_similarity(vector)

# reduce file volume by only filter top 10 closest similarity values
top_n = 10
similarity_sparse = np.zeros_like(similarity)

for i in range(similarity.shape[0]):
    top_indices = similarity[i].argsort()[-top_n:]
    similarity_sparse[i, top_indices] = similarity[i, top_indices]
similarity = similarity_sparse
print(similarity)

[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [414]:
#Try to test similarity with index = 2 and get first 5 values
similarity[2][:5]

array([0., 0., 1., 0., 0.])

In [415]:
# Determine index
index = df_movies_final[df_movies_final['original_title']=='Spectre'].index[0]
index

2

In [416]:
similarity[index]

array([0., 0., 1., ..., 0., 0., 0.])

In [417]:
# Get all values which similar with index 
distances = sorted([*enumerate(similarity[index])], key=lambda x: x[1], reverse=True)
distances[:5]

[(2, 0.9999999999999999),
 (11, 0.3633610463437159),
 (1343, 0.34521548171187133),
 (29, 0.321797951467419),
 (4070, 0.28097574347450816)]

In [418]:
# test with index get from distances
df_movies_final.iloc[2]['original_title']

'Spectre'

In [419]:
# Determine all values which have similar values which the first 5 values in distances 
for i in distances[:5]:
    get = df_movies_final.iloc[i[0]]['original_title']
    print(get)

Spectre
Quantum of Solace
Never Say Never Again
Skyfall
From Russia with Love


In [420]:
# create the dynamic function for recommendation app
def recommend(title):
    index = df_movies_final[df_movies_final['original_title']==title].index[0]
    distances = sorted([*enumerate(similarity[index])], key=lambda x: x[1], reverse=True)
    for value in distances[1:6]:
        get = df_movies_final.iloc[value[0]]['original_title']
        print(get)

recommend("Avatar")

Titan A.E.
Small Soldiers
Aliens vs Predator: Requiem
Independence Day
Ender's Game


In [422]:
from joblib import dump

list_model = {
    'similarity' : similarity,
    'dataframe' : df_movies_final
}
dump(list_model,"artifact/save_model.joblib", compress=('zlib', 3))

['artifact/save_model.joblib']